
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Prestlan.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Actividad
{

    public Actividad()
    {

        this.Actividad_translation = new HashSet<Actividad_translation>();

        this.Empresa = new HashSet<Empresa>();

        this.Trabajador = new HashSet<Trabajador>();

    }


    public int Id { get; set; }

    public string Descripcion_null { get; set; }



    public virtual ICollection<Actividad_translation> Actividad_translation { get; set; }

    public virtual ICollection<Empresa> Empresa { get; set; }

    public virtual ICollection<Trabajador> Trabajador { get; set; }

}

}
