
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Prestlan.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Configuracion
{

    public int id { get; set; }

    public int alerta_caducidad_1 { get; set; }

    public int alerta_caducidad_2 { get; set; }

    public string nombre_empresa { get; set; }

    public string idioma_general { get; set; }

}

}
