
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Prestlan.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Documento
{

    public Documento()
    {

        this.Documento1 = new HashSet<Documento>();

        this.MovimientosDeDocumento = new HashSet<MovimientosDeDocumento>();

        this.Biblioteca = new HashSet<Biblioteca>();

        this.Propietario = new HashSet<Propietario>();

    }


    public int Id { get; set; }

    public string Titulo { get; set; }

    public string Descripcion { get; set; }

    public bool Caduca { get; set; }

    public Nullable<System.DateTime> FechaCaducidad { get; set; }

    public bool SinPropietarios { get; set; }

    public bool SinNotificaciones { get; set; }

    public System.DateTime FechaCreado { get; set; }

    public System.DateTime FechaActualizado { get; set; }

    public bool Eliminado { get; set; }

    public string HashEmpleado { get; set; }

    public int Fichero_Id { get; set; }

    public Nullable<int> DocumentoVersion_Id { get; set; }

    public int TipoDocumento_Id { get; set; }

    public int Usuario_Id { get; set; }

    public int Estado_Id { get; set; }

    public int Etapa_Id { get; set; }



    public virtual ICollection<Documento> Documento1 { get; set; }

    public virtual Documento Documento2 { get; set; }

    public virtual Fichero Fichero { get; set; }

    public virtual ICollection<MovimientosDeDocumento> MovimientosDeDocumento { get; set; }

    public virtual TipoDocumento TipoDocumento { get; set; }

    public virtual TipoEstado TipoEstado { get; set; }

    public virtual TipoEtapa TipoEtapa { get; set; }

    public virtual Usuario Usuario { get; set; }

    public virtual ICollection<Biblioteca> Biblioteca { get; set; }

    public virtual ICollection<Propietario> Propietario { get; set; }

}

}
