
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Prestlan.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Empresa
{

    public Empresa()
    {

        this.Propietario = new HashSet<Propietario>();

        this.Trabajador = new HashSet<Trabajador>();

        this.Usuario = new HashSet<Usuario>();

    }


    public int Id { get; set; }

    public string ValorIdentificador { get; set; }

    public string Nombre { get; set; }

    public string Direccion { get; set; }

    public string Observaciones { get; set; }

    public string CorreosNotificaciones { get; set; }

    public bool SinNotificaciones { get; set; }

    public bool Activa { get; set; }

    public System.DateTime FechaAlta { get; set; }

    public System.DateTime FechaBaja { get; set; }

    public bool Eliminado { get; set; }

    public int TipoIdentificador_Id { get; set; }

    public int TipoEmpresa_Id { get; set; }

    public int Actividad_Id { get; set; }



    public virtual Actividad Actividad { get; set; }

    public virtual ICollection<Propietario> Propietario { get; set; }

    public virtual ICollection<Trabajador> Trabajador { get; set; }

    public virtual TipoEmpresa TipoEmpresa { get; set; }

    public virtual TipoIdentificador TipoIdentificador { get; set; }

    public virtual ICollection<Usuario> Usuario { get; set; }

}

}
