
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Prestlan.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Fichero
{

    public Fichero()
    {

        this.Documento = new HashSet<Documento>();

    }


    public int Id { get; set; }

    public string nombre { get; set; }

    public System.DateTime FechaCreado { get; set; }

    public string nombreFS { get; set; }



    public virtual ICollection<Documento> Documento { get; set; }

}

}
