
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Prestlan.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MovimientosDeDocumento
{

    public MovimientosDeDocumento()
    {

        this.Notificaciones = new HashSet<Notificaciones>();

    }


    public int Id { get; set; }

    public string descripcion { get; set; }

    public System.DateTime fechaOperacion { get; set; }

    public int Documento_Id { get; set; }

    public int Usuario_Id { get; set; }

    public int TipoEstado_Id { get; set; }

    public int TipoEtapa_Id { get; set; }



    public virtual ICollection<Notificaciones> Notificaciones { get; set; }

    public virtual TipoEstado TipoEstado { get; set; }

    public virtual TipoEtapa TipoEtapa { get; set; }

    public virtual Usuario Usuario { get; set; }

    public virtual Documento Documento { get; set; }

}

}
