
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Prestlan.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Notificaciones
{

    public int Id { get; set; }

    public string correoEmisor { get; set; }

    public string correoDestinatario { get; set; }

    public string asunto { get; set; }

    public string contenido { get; set; }

    public bool envioCorreoExito { get; set; }

    public System.DateTime fechaNotificacion { get; set; }

    public int MovimientosDeDocumento_Id { get; set; }



    public virtual MovimientosDeDocumento MovimientosDeDocumento { get; set; }

}

}
