
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Prestlan.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Propietario
{

    public Propietario()
    {

        this.Documento = new HashSet<Documento>();

    }


    public int Id { get; set; }

    public Nullable<int> Empresa_Id { get; set; }

    public Nullable<int> Trabajador_Id { get; set; }



    public virtual Empresa Empresa { get; set; }

    public virtual Trabajador Trabajador { get; set; }

    public virtual ICollection<Documento> Documento { get; set; }

}

}
