
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Prestlan.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Requisitos
{

    public Requisitos()
    {

        this.TipoDocumento = new HashSet<TipoDocumento>();

    }


    public int Id { get; set; }

    public string descripcion { get; set; }



    public virtual ICollection<TipoDocumento> TipoDocumento { get; set; }

}

}
