
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Prestlan.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TipoEmpresa
{

    public TipoEmpresa()
    {

        this.Empresa = new HashSet<Empresa>();

        this.TipoEmpresa_translation = new HashSet<TipoEmpresa_translation>();

    }


    public int Id { get; set; }

    public bool Activo { get; set; }

    public Nullable<bool> EsEmpresaPrincipal { get; set; }



    public virtual ICollection<Empresa> Empresa { get; set; }

    public virtual ICollection<TipoEmpresa_translation> TipoEmpresa_translation { get; set; }

}

}
