
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Prestlan.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TipoEtapa
{

    public TipoEtapa()
    {

        this.MovimientosDeDocumento = new HashSet<MovimientosDeDocumento>();

        this.Documento = new HashSet<Documento>();

    }


    public int Id { get; set; }

    public string descripcion { get; set; }



    public virtual ICollection<MovimientosDeDocumento> MovimientosDeDocumento { get; set; }

    public virtual ICollection<Documento> Documento { get; set; }

}

}
