
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Prestlan.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TipoTrabajador
{

    public TipoTrabajador()
    {

        this.TipoTrabajador_translation = new HashSet<TipoTrabajador_translation>();

        this.Trabajador = new HashSet<Trabajador>();

    }


    public int Id { get; set; }

    public bool Activo { get; set; }



    public virtual ICollection<TipoTrabajador_translation> TipoTrabajador_translation { get; set; }

    public virtual ICollection<Trabajador> Trabajador { get; set; }

}

}
