
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Prestlan.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Trabajador
{

    public Trabajador()
    {

        this.Propietario = new HashSet<Propietario>();

        this.Actividad = new HashSet<Actividad>();

    }


    public int Id { get; set; }

    public string ValorIdentificador { get; set; }

    public string Nombre { get; set; }

    public bool Activo { get; set; }

    public System.DateTime FechaAlta { get; set; }

    public System.DateTime FechaBaja { get; set; }

    public bool Eliminado { get; set; }

    public int TipoIdentificador_Id { get; set; }

    public int Empresa_Id { get; set; }

    public int TipoTrabajador_Id { get; set; }

    public bool Autonomo { get; set; }

    public string Observaciones { get; set; }



    public virtual Empresa Empresa { get; set; }

    public virtual ICollection<Propietario> Propietario { get; set; }

    public virtual TipoIdentificador TipoIdentificador { get; set; }

    public virtual TipoTrabajador TipoTrabajador { get; set; }

    public virtual ICollection<Actividad> Actividad { get; set; }

}

}
