
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Prestlan.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Usuario
{

    public Usuario()
    {

        this.MovimientosDeDocumento = new HashSet<MovimientosDeDocumento>();

        this.Documento = new HashSet<Documento>();

    }


    public int Id { get; set; }

    public string nombre { get; set; }

    public string email { get; set; }

    public string clave { get; set; }

    public System.DateTime fechaAlta { get; set; }

    public Nullable<System.DateTime> fechaBaja { get; set; }

    public Nullable<System.DateTime> ultimoLogin { get; set; }

    public int Rol_Id { get; set; }

    public string ip { get; set; }

    public string idioma { get; set; }

    public int Empresa_Id { get; set; }



    public virtual ICollection<MovimientosDeDocumento> MovimientosDeDocumento { get; set; }

    public virtual ICollection<Documento> Documento { get; set; }

    public virtual Rol Rol { get; set; }

    public virtual Empresa Empresa { get; set; }

}

}
